using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;

namespace DockBar.Services;

public static class LocalizationService
{
    private static readonly Dictionary<string, Dictionary<string, string>> RawStrings = new()
    {
        ["es"] = new Dictionary<string, string>
        {
            ["Common_Save"] = "Guardar",
            ["Common_Apply"] = "Aplicar",
            ["Common_Cancel"] = "Cancelar",
            ["Common_Close"] = "Cerrar",
            ["Common_Add"] = "Agregar",
            ["Common_About"] = "Acerca de",
            ["Common_Page"] = "Página",

            ["Settings_Title"] = "Ajustes",
            ["Settings_Subtitle"] = "Haz que el dock se sienta tuyo: ajusta tamaño, respuesta y acabado visual con vista previa en tiempo real.",
            ["Settings_Size"] = "Tamaño",
            ["Settings_SizeHint"] = "Define cuánto espacio ocupa la barra y qué protagonismo tienen los accesos.",
            ["Settings_DockWidth"] = "Ancho de barra (px)",
            ["Settings_IconSize"] = "Tamaño de ícono (px)",
            ["Settings_AutoHide"] = "Auto-ocultamiento y animación",
            ["Settings_BehaviorHint"] = "Ajusta el ritmo con el que aparece y se oculta para que se sienta suave, no torpe.",
            ["Settings_HideDelay"] = "Retardo al ocultar (segundos, 0 = inmediato estilo Win8)",
            ["Settings_AnimDuration"] = "Duración de la animación al ocultar y mostrar (ms)",
            ["Settings_AutoStart"] = "Iniciar con Windows",
            ["Settings_ColorTransparency"] = "Color y efecto Glass",
            ["Settings_AppearanceHint"] = "Ajusta el color base y decide si el dock usa un acabado Glass o un fondo sólido.",
            ["Settings_UseTransparency"] = "Activar efecto Glass",
            ["Settings_Opacity"] = "Opacidad",
            ["Settings_GlassEffect"] = "Efecto Glass",
            ["Settings_GlassOn"] = "Activo",
            ["Settings_GlassOff"] = "Inactivo",
            ["Settings_ColorPicker"] = "Selector de color (HEX y lienzo)",
            ["Settings_ColorPickerBg"] = "Color de fondo (HEX y lienzo)",
            ["Settings_ColorPickerAccent"] = "Color de énfasis / botones (HEX y lienzo)",
            ["Settings_ColorTarget"] = "Elemento a personalizar:",
            ["Settings_ColorTargetBg"] = "🎨 Fondo del dock",
            ["Settings_ColorTargetAccent"] = "⚡ Énfasis / Botones",
            ["Settings_ColorHint"] = "Elige un tono con el lienzo HSV o escribe el valor HEX manualmente.",
            ["Settings_Preview"] = "Vista previa",
            ["Settings_PreviewHint"] = "Una referencia rápida de cómo se verán el fondo, el texto y la densidad visual.",
            ["Settings_PreviewSummary"] = "Resumen actual",
            ["Settings_HexLabel"] = "Color HEX",
            ["Settings_HexLabelBg"] = "HEX (Fondo)",
            ["Settings_HexLabelAccent"] = "HEX (Énfasis)",
            ["Settings_ColorPalette"] = "Paleta rápida (Fondo)",
            ["Settings_ColorPaletteHint"] = "Puntos de partida equilibrados para no comenzar desde cero.",
            ["Settings_AccentPalette"] = "Paleta de énfasis (Botones y controles)",
            ["Settings_AccentPaletteHint"] = "Color de contraste para botones de acción, deslizadores e interactivos.",
            ["Settings_TextColor"] = "Color de texto:",
            ["Settings_TextLight"] = "Claro (blanco)",
            ["Settings_TextDark"] = "Oscuro (negro)",
            ["Settings_TextShadow"] = "Sombra de texto:",
            ["Settings_TextShadowOption"] = "Sombra dinámica a letras",
            ["Settings_DefaultConfig"] = "Restaurar base",
            ["Settings_FooterHint"] = "La vista previa refleja los cambios al instante antes de guardarlos.",
            ["Settings_TabBasic"] = "Configuración básica",
            ["Settings_TabClock"] = "Reloj",
            ["Settings_TabMedia"] = "Multimedia",
            ["Settings_TabExperimental"] = "Experimental",
            ["Settings_ExperimentalBanner"] = "Funciones experimentales",
            ["Settings_ExperimentalHint"] = "Características en desarrollo para expandir las capacidades de DockBar.",
            ["Settings_ExperimentalEmptyTitle"] = "Sin funciones experimentales activas",
            ["Settings_ExperimentalEmptyHint"] = "Actualmente no hay funciones experimentales en desarrollo. Próximamente se añadirán nuevas características aquí.",
            ["Settings_ShowResourceMonitor"] = "Monitor de recursos (CPU, RAM y GPU)",
            ["Settings_ShowResourceMonitorDesc"] = "Muestra el uso de procesador, memoria y tarjetas gráficas en tiempo real en el dock. Clic para abrir el Administrador de tareas.",
            ["Settings_ShowCaffeine"] = "Modo Caffeine (Mantener pantalla activa)",
            ["Settings_ShowCaffeineDesc"] = "Añade un botón en el dock para evitar con 1 clic que la pantalla se apague o el equipo entre en suspensión.",
            ["Dock_CaffeineActiveTooltip"] = "Caffeine: ACTIVO (Pantalla siempre despierta)&#x0a;Clic para desactivar",
            ["Dock_CaffeineInactiveTooltip"] = "Caffeine: INACTIVO (Modo normal de energía)&#x0a;Clic para mantener pantalla despierta",
            ["Dock_ResourceMonitorTooltip"] = "Monitor del sistema&#x0a;Clic para abrir el Administrador de tareas",
            ["Settings_WidgetResource"] = "Recursos (CPU/RAM/GPU)",
            ["Settings_DetectedGpus"] = "GPUs detectadas",
            ["Settings_DetectedGpuSingle"] = "GPU detectada",
            ["Settings_ShowHardwareModelNames"] = "Mostrar nombres de modelos de hardware (CPU / GPU)",
            ["Settings_ShowHardwareModelNamesDesc"] = "Muestra el modelo de procesador y tarjeta gráfica (ej. i5 210H, RTX 5050, Ryzen 7) en vez de etiquetas genéricas.",
            ["Settings_WidgetCaffeine"] = "Caffeine",
            ["Settings_ClockSection"] = "Reloj en tiempo real",
            ["Settings_ClockSectionHint"] = "Aprovecha el espacio libre de la barra donde no cabe otro programa para mostrar la hora y fecha como en Windows.",
            ["Settings_ShowClock"] = "Mostrar reloj en el dock",
            ["Settings_Clock24H"] = "Formato de 24 horas (ej. 14:30)",
            ["Settings_ClockSeconds"] = "Mostrar segundos en tiempo real",
            ["Settings_ClockDate"] = "Mostrar fecha debajo de la hora",
            ["Settings_ClockFontSize"] = "Tamaño de fuente del reloj (px)",
            ["Settings_ClockPreview"] = "Vista previa de la dockbar",
            ["Settings_DragReorderTooltip"] = "Arrastra para cambiar el orden en el dock",
            ["Settings_WidgetOrderTitle"] = "Orden de los widgets en el dock:",
            ["Settings_WidgetClock"] = "Reloj",
            ["Settings_WidgetMedia"] = "Multimedia / Título",
            ["Settings_WidgetVolume"] = "Volumen",
            ["Settings_WidgetDisabledTag"] = " (Desactivado)",
            ["Settings_MoveUp"] = "Subir",
            ["Settings_MoveDown"] = "Bajar",
            ["Settings_TriggerSection"] = "Activador de borde (Hotspot)",
            ["Settings_TriggerSectionHint"] = "Configura el grosor en píxeles del área del borde que activa la aparición del dock. Redúcelo para pegar más el cursor al borde.",
            ["Settings_TriggerThickness"] = "Grosor del activador del borde (px)",
            ["Settings_VolumeSection"] = "Controlador de volumen",
            ["Settings_VolumeSectionHint"] = "Permite regular el volumen del sistema y silenciar el audio directamente desde el dock.",
            ["Settings_ShowVolume"] = "Mostrar controlador de volumen en el dock",
            ["Settings_MediaSection"] = "Controlador multimedia inteligente",
            ["Settings_MediaSectionHint"] = "Conecta con Spotify, navegadores (YouTube) y reproductores de Windows para mostrar la música en reproducción con texto en movimiento y controles.",
            ["Settings_ShowMedia"] = "Mostrar controlador multimedia en el dock",
            ["Settings_ShowMediaSeekBar"] = "Mostrar barra de progreso / búsqueda de reproducción",
            ["Settings_ShowMediaSeekBarDesc"] = "Muestra la línea de tiempo y un control deslizante para adelantar o retroceder el audio o video.",
            ["Dock_MediaPlayPause"] = "Reproducir / Pausar",
            ["Dock_MediaNext"] = "Siguiente pista",
            ["Dock_MediaPrev"] = "Pista anterior",
            ["Dock_MediaNoTrack"] = "Sin reproducción activa",
            ["Dock_VolumeMute"] = "Silenciar audio",
            ["Dock_VolumeUnmute"] = "Activar sonido",
            ["Settings_ApplyConfirmTitle"] = "Confirmar configuración",
            ["Settings_ApplyConfirmMessage"] = "¿Deseas guardar los cambios aplicados?",
            ["Settings_ApplyCountdownText"] = "Se revertirá automáticamente en {0} segundos...",

            ["AddLink_Title"] = "Agregar app o acceso",
            ["AddLink_Subtitle"] = "Pega una ruta, un ejecutable, una carpeta o un comando y dale un nombre limpio para el dock.",
            ["AddLink_Target"] = "Ruta, ejecutable o comando",
            ["AddLink_TargetHint"] = "Puedes usar un .exe, una carpeta, una URI o un comando compatible con Windows.",
            ["AddLink_NameOptional"] = "Nombre visible (opcional)",
            ["AddLink_NameHint"] = "Si lo dejas vacío, DockBar intentará usar un nombre detectado automáticamente.",
            ["AddLink_ExamplesTitle"] = "Ejemplos útiles",
            ["AddLink_ExamplesBody"] = "Úsalo cuando quieras agregar una app externa, una carpeta frecuente o un acceso por comando.",
            ["AddLink_ExamplesFooter"] = "Para apps instaladas del sistema, usa el selector de la opción “Apps instaladas...”.",
            ["AddLink_ValidationEmpty"] = "Escribe una ruta, URI o comando antes de guardar.",
            ["AddLink_ValidationInvalid"] = "La ruta o comando no parece válido. Usa un archivo existente, una carpeta, una URI o un comando ejecutable de Windows.",

            ["Rename_Title"] = "Renombrar acceso",
            ["Rename_Subtitle"] = "Cambia el nombre visible del acceso sin modificar su destino.",
            ["Rename_NewName"] = "Nuevo nombre",

            ["Store_Title"] = "Apps instaladas",
            ["Store_Subtitle"] = "Explora las aplicaciones detectadas en Windows y agrégalas al dock con su ícono del sistema.",
            ["Store_Search"] = "Buscar app",
            ["Store_SearchHint"] = "Puedes buscar por nombre visible, identificador interno o parte del paquete.",
            ["Store_Refresh"] = "Actualizar",
            ["Store_RefreshTooltip"] = "Volver a escanear aplicaciones instaladas",
            ["Store_Loading"] = "Cargando apps instaladas...",
            ["Store_Empty"] = "No se encontraron apps instaladas.",
            ["Store_NoApps"] = "No se encontraron apps instaladas.",
            ["Store_PanelTitle"] = "Selección rápida",
            ["Store_PanelBody"] = "Este panel está pensado para sumar apps instaladas sin tener que pegar rutas manualmente.",
            ["Store_PanelTipOneTitle"] = "Qué vas a encontrar",
            ["Store_PanelTipOneBody"] = "Apps UWP, accesos detectados por Windows y entradas que exponen un identificador ejecutable.",
            ["Store_PanelTipTwoTitle"] = "Cómo elegir mejor",
            ["Store_PanelTipTwoBody"] = "Si ves nombres parecidos, revisa el identificador inferior para distinguir la app correcta.",
            ["Store_PanelFooter"] = "Doble clic también agrega la app seleccionada.",
            ["Store_FooterHint"] = "Doble clic también agrega la app seleccionada.",

            ["Tray_Open"] = "Abrir",
            ["Tray_ToggleSide"] = "Cambiar lado",
            ["Tray_Settings"] = "Ajustes...",
            ["Tray_ConfigFolder"] = "Configuración",
            ["Update_Menu"] = "Actualizar...",
            ["Tray_Exit"] = "Salir",

            ["AddMenu_File"] = "Archivo / ejecutable...",
            ["AddMenu_Store"] = "Apps instaladas...",
            ["AddMenu_Uri"] = "Comando / URI...",
            ["Dock_TooltipAdd"] = "Agregar acceso",
            ["Dock_TooltipSettings"] = "Abrir ajustes",
            ["Dock_TooltipEditMode"] = "Activar modo edición",
            ["Dock_TooltipClose"] = "Cerrar DockBar",
            ["Dock_TooltipRename"] = "Renombrar",
            ["Dock_TooltipChangeIcon"] = "Cambiar ícono",
            ["Dock_TooltipRemove"] = "Eliminar acceso",

            ["Dialog_SelectShortcutTitle"] = "Selecciona acceso directo o ejecutable",
            ["Dialog_ExecutableFilter"] = "Ejecutables y accesos (*.exe;*.lnk;*.url)|*.exe;*.lnk;*.url|Todos los archivos (*.*)|*.*",
            ["Dialog_SelectIconTitle"] = "Selecciona ícono o imagen",
            ["Dialog_ImageFilter"] = "Imágenes e íconos (*.png;*.ico;*.jpg;*.jpeg;*.bmp)|*.png;*.ico;*.jpg;*.jpeg;*.bmp|Todos los archivos (*.*)|*.*",

            ["Config_NotFound"] = "No se encontró configuración previa. Se creó una nueva en AppData.",
            ["Config_ReadError"] = "El archivo de configuración estaba dañado o no se pudo leer. Se restauraron los valores por defecto.",

            ["AutoStart_Prompt"] = "¿Deseas que DockBar se inicie automáticamente al encender tu equipo?",
            ["AutoStart_Title"] = "Inicio automático",

            ["Update_Title"] = "Actualización de DockBar",
            ["Update_Subtitle"] = "Una nueva versión de DockBar está disponible con mejoras y correcciones.",
            ["Update_Checking"] = "Buscando actualizaciones...",
            ["Update_LatestTitle"] = "DockBar actualizado",
            ["Update_LatestBody"] = "Ya estás usando la versión más reciente ({0}).",
            ["Update_Available"] = "Hay una nueva versión disponible ({0}). ¿Deseas descargarla e instalarla ahora?",
            ["Update_AvailableTitle"] = "Nueva versión disponible",
            ["Update_AvailableBody"] = "Versión actual: {0}\nNueva versión: {1}\n\n¿Deseas actualizar ahora?",
            ["Update_CheckFailed"] = "No se pudo comprobar si hay actualizaciones disponibles.",
            ["Update_UpToDate"] = "DockBar ya está actualizado a la versión más reciente ({0}).",
            ["Update_NoInstaller"] = "No se encontró el instalador ejecutable para la versión {0}.",
            ["Update_CurrentVersion"] = "Versión actual",
            ["Update_NewVersion"] = "Nueva versión",
            ["Update_InstallNow"] = "Actualizar ahora",
            ["Update_Later"] = "Más tarde",
            ["Update_Changelog"] = "Novedades de la versión",
            ["Update_NoChangelog"] = "Esta versión incluye optimizaciones y mejoras generales de rendimiento.",
            ["Update_StatusReady"] = "Listo para descargar e instalar la actualización.",
            ["Update_StatusDownloading"] = "Descargando actualización...",
            ["Update_StatusDownloaded"] = "Descarga completada. Iniciando instalador...",
            ["Update_Downloading"] = "Descargando actualización...",
            ["Update_DownloadFailed"] = "No se pudo descargar la actualización.",
            ["Update_ErrorTitle"] = "Error al buscar actualizaciones",
            ["Update_ErrorBody"] = "Ocurrió un error al verificar actualizaciones.",
            ["Update_PackagedManaged"] = "DockBar está instalada como paquete MSIX. Las actualizaciones se gestionan automáticamente a través de la Microsoft Store / Windows.",
            ["Update_OpenReleasePage"] = "Ver en GitHub",

            ["About_Title"] = "Acerca de DockBar",
            ["About_Subtitle"] = "Información del sistema y versión actual",
            ["About_Version"] = "Versión",
            ["About_UnknownVersion"] = "desconocida",
            ["About_DeveloperCaption"] = "Desarrollado por",
            ["About_DeveloperName"] = "Eliather",
            ["About_DescriptionText"] = "Barra lateral de accesos directos para Windows.",
            ["About_ConfigLabel"] = "Archivo de configuración",
            ["About_DevelopedBy"] = "Desarrollado por Eliather",
            ["About_Description"] = "Descripción: barra lateral de accesos directos para Windows.",
            ["About_ConfigPath"] = "Configuración: %AppData%\\DockBar\\shortcuts.json"
        },
        ["en"] = new Dictionary<string, string>
        {
            ["Common_Save"] = "Save",
            ["Common_Apply"] = "Apply",
            ["Common_Cancel"] = "Cancel",
            ["Common_Close"] = "Close",
            ["Common_Add"] = "Add",
            ["Common_About"] = "About",
            ["Common_Page"] = "Page",

            ["Settings_Title"] = "Settings",
            ["Settings_Subtitle"] = "Make the dock yours: adjust size, response, and visual finish with live preview.",
            ["Settings_Size"] = "Size",
            ["Settings_SizeHint"] = "Set dock width and shortcut prominence.",
            ["Settings_DockWidth"] = "Dock width (px)",
            ["Settings_IconSize"] = "Icon size (px)",
            ["Settings_AutoHide"] = "Auto-hide & animation",
            ["Settings_BehaviorHint"] = "Tune reveal and hide speed for a smooth interaction.",
            ["Settings_HideDelay"] = "Hide delay (seconds, 0 = immediate Win8 style)",
            ["Settings_AnimDuration"] = "Hide/show animation duration (ms)",
            ["Settings_AutoStart"] = "Start with Windows",
            ["Settings_ColorTransparency"] = "Color & Glass effect",
            ["Settings_AppearanceHint"] = "Adjust base color and toggle solid or Glass background.",
            ["Settings_UseTransparency"] = "Enable Glass effect",
            ["Settings_Opacity"] = "Opacity",
            ["Settings_GlassEffect"] = "Glass effect",
            ["Settings_GlassOn"] = "Active",
            ["Settings_GlassOff"] = "Inactive",
            ["Settings_ColorPicker"] = "Color picker (HEX & canvas)",
            ["Settings_ColorPickerBg"] = "Background color (HEX & canvas)",
            ["Settings_ColorPickerAccent"] = "Accent / button color (HEX & canvas)",
            ["Settings_ColorTarget"] = "Color target:",
            ["Settings_ColorTargetBg"] = "🎨 Dock background",
            ["Settings_ColorTargetAccent"] = "⚡ Accent / Buttons",
            ["Settings_ColorHint"] = "Pick a hue using HSV or enter a HEX value.",
            ["Settings_Preview"] = "Preview",
            ["Settings_PreviewHint"] = "Quick reference for background, text, and visual balance.",
            ["Settings_PreviewSummary"] = "Current summary",
            ["Settings_HexLabel"] = "HEX color",
            ["Settings_HexLabelBg"] = "HEX (Background)",
            ["Settings_HexLabelAccent"] = "HEX (Accent)",
            ["Settings_ColorPalette"] = "Quick palette (Background)",
            ["Settings_ColorPaletteHint"] = "Balanced presets so you don't start from scratch.",
            ["Settings_AccentPalette"] = "Accent palette (Buttons & controls)",
            ["Settings_AccentPaletteHint"] = "Contrast color for action buttons, sliders, and interactive controls.",
            ["Settings_TextColor"] = "Text color:",
            ["Settings_TextLight"] = "Light (white)",
            ["Settings_TextDark"] = "Dark (black)",
            ["Settings_TextShadow"] = "Text shadow:",
            ["Settings_TextShadowOption"] = "Dynamic letter shadow",
            ["Settings_DefaultConfig"] = "Restore defaults",
            ["Settings_FooterHint"] = "Preview reflects changes instantly before saving.",
            ["Settings_TabBasic"] = "Basic Settings",
            ["Settings_TabClock"] = "Clock",
            ["Settings_TabMedia"] = "Media",
            ["Settings_TabExperimental"] = "Experimental",
            ["Settings_ExperimentalBanner"] = "Experimental Features",
            ["Settings_ExperimentalHint"] = "Features in active development to expand DockBar capabilities.",
            ["Settings_ExperimentalEmptyTitle"] = "No active experimental features",
            ["Settings_ExperimentalEmptyHint"] = "There are currently no active experimental features. New capabilities under development will be added here soon.",
            ["Settings_ShowResourceMonitor"] = "Resource Monitor (CPU, RAM & GPU)",
            ["Settings_ShowResourceMonitorDesc"] = "Displays real-time CPU, RAM, and graphics cards usage on the dock. Click to open Task Manager.",
            ["Settings_ShowCaffeine"] = "Caffeine Mode (Keep Screen Awake)",
            ["Settings_ShowCaffeineDesc"] = "Adds a button on the dock to prevent the screen from sleeping or turning off with 1 click.",
            ["Dock_CaffeineActiveTooltip"] = "Caffeine: ACTIVE (Screen kept awake)&#x0a;Click to disable",
            ["Dock_CaffeineInactiveTooltip"] = "Caffeine: INACTIVE (Normal power mode)&#x0a;Click to keep screen awake",
            ["Dock_ResourceMonitorTooltip"] = "System Monitor&#x0a;Click to open Task Manager",
            ["Settings_WidgetResource"] = "Resources (CPU/RAM/GPU)",
            ["Settings_DetectedGpus"] = "Detected GPUs",
            ["Settings_DetectedGpuSingle"] = "Detected GPU",
            ["Settings_ShowHardwareModelNames"] = "Show hardware model names (CPU / GPU)",
            ["Settings_ShowHardwareModelNamesDesc"] = "Displays your processor and graphics card models (e.g. i5 210H, RTX 5050, Ryzen 7) instead of generic labels.",
            ["Settings_WidgetCaffeine"] = "Caffeine",
            ["Settings_ClockSection"] = "Real-Time Clock",
            ["Settings_ClockSectionHint"] = "Utilize free space on the dock where another program doesn't fit to display time and date like Windows.",
            ["Settings_ShowClock"] = "Show clock on the dock",
            ["Settings_Clock24H"] = "24-hour format (e.g. 14:30)",
            ["Settings_ClockSeconds"] = "Show seconds in real time",
            ["Settings_ClockDate"] = "Show date under time",
            ["Settings_ClockFontSize"] = "Clock font size (px)",
            ["Settings_ClockPreview"] = "DockBar preview",
            ["Settings_DragReorderTooltip"] = "Drag to reorder widgets on the dock",
            ["Settings_WidgetOrderTitle"] = "Widget order on the dock:",
            ["Settings_WidgetClock"] = "Clock",
            ["Settings_WidgetMedia"] = "Media / Song title",
            ["Settings_WidgetVolume"] = "Volume",
            ["Settings_WidgetDisabledTag"] = " (Disabled)",
            ["Settings_MoveUp"] = "Move up",
            ["Settings_MoveDown"] = "Move down",
            ["Settings_TriggerSection"] = "Edge Trigger (Hotspot)",
            ["Settings_TriggerSectionHint"] = "Set the pixel thickness of the screen edge area that triggers the dock. Lower it to require moving the cursor closer to the edge.",
            ["Settings_TriggerThickness"] = "Edge trigger thickness (px)",
            ["Settings_VolumeSection"] = "Volume Controller",
            ["Settings_VolumeSectionHint"] = "Control system volume and toggle mute directly from the dock.",
            ["Settings_ShowVolume"] = "Show volume controller on the dock",
            ["Settings_MediaSection"] = "Smart Media Controller",
            ["Settings_MediaSectionHint"] = "Connects to Spotify, browsers (YouTube), and Windows media players to display now playing track with animated marquee text and playback controls.",
            ["Settings_ShowMedia"] = "Show media controller on the dock",
            ["Settings_ShowMediaSeekBar"] = "Show playback progress / seek bar",
            ["Settings_ShowMediaSeekBarDesc"] = "Displays the timeline and a slider to fast-forward or rewind audio or video.",
            ["Dock_MediaPlayPause"] = "Play / Pause",
            ["Dock_MediaNext"] = "Next track",
            ["Dock_MediaPrev"] = "Previous track",
            ["Dock_MediaNoTrack"] = "No media playing",
            ["Dock_VolumeMute"] = "Mute audio",
            ["Dock_VolumeUnmute"] = "Unmute audio",
            ["Settings_ApplyConfirmTitle"] = "Confirm Settings",
            ["Settings_ApplyConfirmMessage"] = "Do you want to keep these changes?",
            ["Settings_ApplyCountdownText"] = "Changes will be automatically reverted in {0} seconds...",

            ["AddLink_Title"] = "Add app or shortcut",
            ["AddLink_Subtitle"] = "Paste a path, executable, folder, or command and give it a clean name.",
            ["AddLink_Target"] = "Path, executable, or command",
            ["AddLink_TargetHint"] = "Use a .exe, folder, URI, or supported Windows command.",
            ["AddLink_NameOptional"] = "Display name (optional)",
            ["AddLink_NameHint"] = "If left empty, DockBar will auto-detect a name.",
            ["AddLink_ExamplesTitle"] = "Useful examples",
            ["AddLink_ExamplesBody"] = "Use this to add an external app, frequent folder, or command shortcut.",
            ["AddLink_ExamplesFooter"] = "For installed system apps, use 'Installed apps...' picker.",
            ["AddLink_ValidationEmpty"] = "Enter a path, URI, or command before saving.",
            ["AddLink_ValidationInvalid"] = "The path or command appears invalid. Use an existing file, folder, URI, or Windows command.",

            ["Rename_Title"] = "Rename shortcut",
            ["Rename_Subtitle"] = "Change the visible shortcut name without changing its target.",
            ["Rename_NewName"] = "New name",

            ["Store_Title"] = "Installed apps",
            ["Store_Subtitle"] = "Browse detected Windows apps and add them with system icons.",
            ["Store_Search"] = "Search app",
            ["Store_SearchHint"] = "Search by display name, internal ID, or package string.",
            ["Store_Refresh"] = "Refresh",
            ["Store_RefreshTooltip"] = "Re-scan installed applications",
            ["Store_Loading"] = "Loading installed apps...",
            ["Store_Empty"] = "No installed apps found.",
            ["Store_NoApps"] = "No installed apps found.",
            ["Store_PanelTitle"] = "Quick selection",
            ["Store_PanelBody"] = "Designed to add system apps easily without manual paths.",
            ["Store_PanelTipOneTitle"] = "What you'll find",
            ["Store_PanelTipOneBody"] = "UWP apps, system shortcuts, and executable app entries.",
            ["Store_PanelTipTwoTitle"] = "Choosing the right app",
            ["Store_PanelTipTwoBody"] = "If names look similar, check the ID below the item.",
            ["Store_PanelFooter"] = "Double-click also adds the selected app.",
            ["Store_FooterHint"] = "Double-click also adds the selected app.",

            ["Tray_Open"] = "Open",
            ["Tray_ToggleSide"] = "Toggle side",
            ["Tray_Settings"] = "Settings...",
            ["Tray_ConfigFolder"] = "Configuration",
            ["Update_Menu"] = "Check for updates...",
            ["Tray_Exit"] = "Exit",

            ["AddMenu_File"] = "File / executable...",
            ["AddMenu_Store"] = "Installed apps...",
            ["AddMenu_Uri"] = "Command / URI...",
            ["Dock_TooltipAdd"] = "Add shortcut",
            ["Dock_TooltipSettings"] = "Open settings",
            ["Dock_TooltipEditMode"] = "Toggle edit mode",
            ["Dock_TooltipClose"] = "Close DockBar",
            ["Dock_TooltipRename"] = "Rename",
            ["Dock_TooltipChangeIcon"] = "Change icon",
            ["Dock_TooltipRemove"] = "Remove shortcut",

            ["Dialog_SelectShortcutTitle"] = "Select shortcut or executable",
            ["Dialog_ExecutableFilter"] = "Executables and shortcuts (*.exe;*.lnk;*.url)|*.exe;*.lnk;*.url|All files (*.*)|*.*",
            ["Dialog_SelectIconTitle"] = "Select icon or image",
            ["Dialog_ImageFilter"] = "Images and icons (*.png;*.ico;*.jpg;*.jpeg;*.bmp)|*.png;*.ico;*.jpg;*.jpeg;*.bmp|All files (*.*)|*.*",

            ["Config_NotFound"] = "No previous config found. Created a default one in AppData.",
            ["Config_ReadError"] = "Config file was corrupted or unreadable. Restored default values.",

            ["AutoStart_Prompt"] = "Do you want DockBar to launch automatically when your computer starts?",
            ["AutoStart_Title"] = "Auto-Start",

            ["Update_Title"] = "DockBar Update",
            ["Update_Subtitle"] = "A new version of DockBar is available with improvements and fixes.",
            ["Update_Checking"] = "Checking for updates...",
            ["Update_LatestTitle"] = "DockBar up to date",
            ["Update_LatestBody"] = "You are running the latest version ({0}).",
            ["Update_Available"] = "A new version is available ({0}). Do you want to download and install it now?",
            ["Update_AvailableTitle"] = "New version available",
            ["Update_AvailableBody"] = "Current version: {0}\nNew version: {1}\n\nDo you want to update now?",
            ["Update_CheckFailed"] = "Could not check for updates at this time.",
            ["Update_UpToDate"] = "DockBar is up to date with the latest version ({0}).",
            ["Update_NoInstaller"] = "No installer executable was found for version {0}.",
            ["Update_CurrentVersion"] = "Current version",
            ["Update_NewVersion"] = "New version",
            ["Update_InstallNow"] = "Update now",
            ["Update_Later"] = "Later",
            ["Update_Changelog"] = "What's new in this version",
            ["Update_NoChangelog"] = "This release includes optimizations and general performance improvements.",
            ["Update_StatusReady"] = "Ready to download and install update.",
            ["Update_StatusDownloading"] = "Downloading update...",
            ["Update_StatusDownloaded"] = "Download complete. Starting installer...",
            ["Update_Downloading"] = "Downloading update...",
            ["Update_DownloadFailed"] = "Failed to download update.",
            ["Update_ErrorTitle"] = "Update check error",
            ["Update_ErrorBody"] = "An error occurred while checking for updates.",
            ["Update_PackagedManaged"] = "DockBar is running as an MSIX package. Updates are managed automatically through the Microsoft Store / Windows.",
            ["Update_OpenReleasePage"] = "View on GitHub",

            ["About_Title"] = "About DockBar",
            ["About_Subtitle"] = "System information and current version",
            ["About_Version"] = "Version",
            ["About_UnknownVersion"] = "unknown",
            ["About_DeveloperCaption"] = "Developed by",
            ["About_DeveloperName"] = "Eliather",
            ["About_DescriptionText"] = "Shortcut sidebar for Windows.",
            ["About_ConfigLabel"] = "Configuration file",
            ["About_DevelopedBy"] = "Developed by Eliather",
            ["About_Description"] = "Description: shortcut sidebar for Windows.",
            ["About_ConfigPath"] = "Configuration: %AppData%\\DockBar\\shortcuts.json"
        },
        ["ru"] = new Dictionary<string, string>
        {
            ["Common_Save"] = "Сохранить",
            ["Common_Apply"] = "Применить",
            ["Common_Cancel"] = "Отмена",
            ["Common_Close"] = "Закрыть",
            ["Common_Add"] = "Добавить",
            ["Common_About"] = "О программе",
            ["Common_Page"] = "Страница",

            ["Settings_Title"] = "Настройки",
            ["Settings_Subtitle"] = "Персонализируйте dock-панель: настройте размер, отклик и внешний вид с предпросмотром в реальном времени.",
            ["Settings_Size"] = "Размер",
            ["Settings_SizeHint"] = "Определяет ширину панели и размер значков быстрого доступа.",
            ["Settings_DockWidth"] = "Ширина панели (пкс)",
            ["Settings_IconSize"] = "Размер значков (пкс)",
            ["Settings_AutoHide"] = "Автоматическое скрытие и анимация",
            ["Settings_BehaviorHint"] = "Настройте скорость появления и скрытия для плавной и естественной работы.",
            ["Settings_HideDelay"] = "Задержка перед скрытием (сек, 0 = мгновенно в стиле Win8)",
            ["Settings_AnimDuration"] = "Длительность анимации скрытия и показа (мс)",
            ["Settings_AutoStart"] = "Запускать вместе с Windows",
            ["Settings_ColorTransparency"] = "Цвет и эффект Glass",
            ["Settings_AppearanceHint"] = "Выберите основной цвет и переключайтесь между эффектом Glass и сплошным фоном.",
            ["Settings_UseTransparency"] = "Включить эффект Glass",
            ["Settings_Opacity"] = "Непрозрачность",
            ["Settings_GlassEffect"] = "Эффект Glass",
            ["Settings_GlassOn"] = "Включен",
            ["Settings_GlassOff"] = "Выключен",
            ["Settings_ColorPicker"] = "Выбор цвета (HEX и палитра)",
            ["Settings_ColorPickerBg"] = "Цвет фона (HEX и палитра)",
            ["Settings_ColorPickerAccent"] = "Цвет акцента / кнопок (HEX и палитра)",
            ["Settings_ColorTarget"] = "Настраиваемый элемент:",
            ["Settings_ColorTargetBg"] = "🎨 Фон панели",
            ["Settings_ColorTargetAccent"] = "⚡ Акцент / Кнопки",
            ["Settings_ColorHint"] = "Выберите оттенок в палитре HSV или введите значение HEX вручную.",
            ["Settings_Preview"] = "Предпросмотр",
            ["Settings_PreviewHint"] = "Наглядный пример того, как будут выглядеть фон, текст и баланс интерфейса.",
            ["Settings_PreviewSummary"] = "Текущие параметры",
            ["Settings_HexLabel"] = "Цвет HEX",
            ["Settings_HexLabelBg"] = "HEX (Фон)",
            ["Settings_HexLabelAccent"] = "HEX (Акцент)",
            ["Settings_ColorPalette"] = "Быстрая палитра (Фон)",
            ["Settings_ColorPaletteHint"] = "Готовые гармоничные цвета для быстрого старта.",
            ["Settings_AccentPalette"] = "Палитра акцентов (Кнопки и элементы)",
            ["Settings_AccentPaletteHint"] = "Контрастный цвет для кнопок действий, ползунков и интерактива.",
            ["Settings_TextColor"] = "Цвет текста:",
            ["Settings_TextLight"] = "Светлый (белый)",
            ["Settings_TextDark"] = "Темный (черный)",
            ["Settings_TextShadow"] = "Тень текста:",
            ["Settings_TextShadowOption"] = "Динамическая тень букв",
            ["Settings_DefaultConfig"] = "По умолчанию",
            ["Settings_FooterHint"] = "Все изменения мгновенно отображаются в предпросмотре до сохранения.",
            ["Settings_TabBasic"] = "Основные настройки",
            ["Settings_TabClock"] = "Часы",
            ["Settings_TabMedia"] = "Медиа",
            ["Settings_TabExperimental"] = "Экспериментальные",
            ["Settings_ExperimentalBanner"] = "Экспериментальные функции",
            ["Settings_ExperimentalHint"] = "Функции в активной разработке для расширения возможностей DockBar.",
            ["Settings_ExperimentalEmptyTitle"] = "Нет активных экспериментальных функций",
            ["Settings_ExperimentalEmptyHint"] = "В настоящее время нет активных экспериментальных функций. Новые возможности появятся здесь в скором времени.",
            ["Settings_ShowResourceMonitor"] = "Монитор ресурсов (ЦП, ОЗУ и GPU)",
            ["Settings_ShowResourceMonitorDesc"] = "Отображает загрузку процессора, памяти и видеокарт на панели в реальном времени. Клик для открытия Диспетчера задач.",
            ["Settings_ShowCaffeine"] = "Режим Caffeine (Бодрствование экрана)",
            ["Settings_ShowCaffeineDesc"] = "Добавляет кнопку на панель, позволяющую в 1 клик предотвратить отключение экрана или спящий режим.",
            ["Dock_CaffeineActiveTooltip"] = "Caffeine: АКТИВЕН (Экран не погаснет)&#x0a;Нажмите для отключения",
            ["Dock_CaffeineInactiveTooltip"] = "Caffeine: НЕАКТИВЕН (Обычный режим)&#x0a;Нажмите для включения",
            ["Dock_ResourceMonitorTooltip"] = "Монитор системы&#x0a;Нажмите для открытия Диспетчера задач",
            ["Settings_WidgetResource"] = "Ресурсы (ЦП/ОЗУ/GPU)",
            ["Settings_DetectedGpus"] = "Обнаруженные GPU",
            ["Settings_DetectedGpuSingle"] = "Обнаруженная GPU",
            ["Settings_ShowHardwareModelNames"] = "Показывать названия моделей (ЦП / GPU)",
            ["Settings_ShowHardwareModelNamesDesc"] = "Отображает модели процессора и видеокарты (напр. i5 210H, RTX 5050, Ryzen 7) вместо стандартных меток.",
            ["Settings_WidgetCaffeine"] = "Caffeine",
            ["Settings_ClockSection"] = "Часы реального времени",
            ["Settings_ClockSectionHint"] = "Используйте свободное пространство панели для отображения даты и времени, как в Windows.",
            ["Settings_ShowClock"] = "Показывать часы на панели",
            ["Settings_Clock24H"] = "24-часовой формат (напр. 14:30)",
            ["Settings_ClockSeconds"] = "Показывать секунды в реальном времени",
            ["Settings_ClockDate"] = "Показывать дату под временем",
            ["Settings_ClockFontSize"] = "Размер шрифта часов (пкс)",
            ["Settings_ClockPreview"] = "Предпросмотр DockBar",
            ["Settings_DragReorderTooltip"] = "Перетащите, чтобы изменить порядок виджетов",
            ["Settings_WidgetOrderTitle"] = "Порядок виджетов на панели:",
            ["Settings_WidgetClock"] = "Часы",
            ["Settings_WidgetMedia"] = "Медиа / Название",
            ["Settings_WidgetVolume"] = "Громкость",
            ["Settings_WidgetDisabledTag"] = " (Отключено)",
            ["Settings_MoveUp"] = "Вверх",
            ["Settings_MoveDown"] = "Вниз",
            ["Settings_TriggerSection"] = "Зона активации у края (Hotspot)",
            ["Settings_TriggerSectionHint"] = "Толщина границы в пикселях, вызывающей появление панели. Уменьшите, чтобы требовалось подводить курсор ближе к краю экрана.",
            ["Settings_TriggerThickness"] = "Толщина зоны активации (пкс)",
            ["Settings_VolumeSection"] = "Регулятор громкости",
            ["Settings_VolumeSectionHint"] = "Управляйте громкостью системы и отключайте звук прямо с dock-панели.",
            ["Settings_ShowVolume"] = "Показывать регулятор громкости на панели",
            ["Settings_MediaSection"] = "Умный медиаплеер",
            ["Settings_MediaSectionHint"] = "Интеграция со Spotify, браузерами (YouTube) и плеерами Windows с бегущей строкой и кнопками управления.",
            ["Settings_ShowMedia"] = "Показывать медиаплеер на панели",
            ["Settings_ShowMediaSeekBar"] = "Показывать полосу прогресса / перемотки",
            ["Settings_ShowMediaSeekBarDesc"] = "Отображает шкалу времени и ползунок для перемотки аудио или видео.",
            ["Dock_MediaPlayPause"] = "Воспроизведение / Пауза",
            ["Dock_MediaNext"] = "Следующий трек",
            ["Dock_MediaPrev"] = "Предыдущий трек",
            ["Dock_MediaNoTrack"] = "Ничего не воспроизводится",
            ["Dock_VolumeMute"] = "Выключить звук",
            ["Dock_VolumeUnmute"] = "Включить звук",
            ["Settings_ApplyConfirmTitle"] = "Подтверждение настроек",
            ["Settings_ApplyConfirmMessage"] = "Сохранить примененные изменения?",
            ["Settings_ApplyCountdownText"] = "Автоматический возврат через {0} сек...",

            ["AddLink_Title"] = "Добавить приложение или ярлык",
            ["AddLink_Subtitle"] = "Укажите путь, исполняемый файл, папку или команду и задайте понятное имя.",
            ["AddLink_Target"] = "Путь, исполняемый файл или команда",
            ["AddLink_TargetHint"] = "Поддерживаются .exe, папки, URI или команды Windows.",
            ["AddLink_NameOptional"] = "Отображаемое имя (необязательно)",
            ["AddLink_NameHint"] = "Если оставить пустым, DockBar определит имя автоматически.",
            ["AddLink_ExamplesTitle"] = "Примеры использования",
            ["AddLink_ExamplesBody"] = "Используйте для добавления сторонних программ, часто используемых папок или ярлыков команд.",
            ["AddLink_ExamplesFooter"] = "Для приложений из Microsoft Store используйте меню «Установленные приложения...».",
            ["AddLink_ValidationEmpty"] = "Введите путь, URI или команду перед сохранением.",
            ["AddLink_ValidationInvalid"] = "Некорректный путь или команда. Укажите существующий файл, папку, URI или команду Windows.",

            ["Rename_Title"] = "Переименовать ярлык",
            ["Rename_Subtitle"] = "Измените отображаемое имя ярлыка без изменения его пути.",
            ["Rename_NewName"] = "Новое имя",

            ["Store_Title"] = "Установленные приложения",
            ["Store_Subtitle"] = "Просматривайте приложения Windows и добавляйте их на панель с системными значками.",
            ["Store_Search"] = "Поиск приложения",
            ["Store_SearchHint"] = "Поиск по названию, внутреннему ID или пакету.",
            ["Store_Refresh"] = "Обновить",
            ["Store_RefreshTooltip"] = "Повторно просканировать установленные приложения",
            ["Store_Loading"] = "Загрузка приложений...",
            ["Store_Empty"] = "Установленные приложения не найдены.",
            ["Store_NoApps"] = "Установленные приложения не найдены.",
            ["Store_PanelTitle"] = "Быстрый выбор",
            ["Store_PanelBody"] = "Позволяет быстро добавлять приложения без необходимости вручную искать пути.",
            ["Store_PanelTipOneTitle"] = "Что доступно",
            ["Store_PanelTipOneBody"] = "Приложения UWP, ярлыки Windows и системные исполняемые компоненты.",
            ["Store_PanelTipTwoTitle"] = "Как выбрать нужное",
            ["Store_PanelTipTwoBody"] = "Если имена похожи, обратите внимание на идентификатор под названием.",
            ["Store_PanelFooter"] = "Двойной клик также добавляет выбранное приложение.",
            ["Store_FooterHint"] = "Двойной клик также добавляет выбранное приложение.",

            ["Tray_Open"] = "Открыть",
            ["Tray_ToggleSide"] = "Переместить на другую сторону",
            ["Tray_Settings"] = "Настройки...",
            ["Tray_ConfigFolder"] = "Папка конфигурации",
            ["Update_Menu"] = "Проверить обновления...",
            ["Tray_Exit"] = "Выход",

            ["AddMenu_File"] = "Файл / исполняемый файл...",
            ["AddMenu_Store"] = "Установленные приложения...",
            ["AddMenu_Uri"] = "Команда / URI...",
            ["Dock_TooltipAdd"] = "Добавить ярлык",
            ["Dock_TooltipSettings"] = "Открыть настройки",
            ["Dock_TooltipEditMode"] = "Режим редактирования",
            ["Dock_TooltipClose"] = "Закрыть DockBar",
            ["Dock_TooltipRename"] = "Переименовать",
            ["Dock_TooltipChangeIcon"] = "Сменить значок",
            ["Dock_TooltipRemove"] = "Удалить ярлык",

            ["Dialog_SelectShortcutTitle"] = "Выберите ярлык или исполняемый файл",
            ["Dialog_ExecutableFilter"] = "Исполняемые файлы и ярлыки (*.exe;*.lnk;*.url)|*.exe;*.lnk;*.url|Все файлы (*.*)|*.*",
            ["Dialog_SelectIconTitle"] = "Выберите значок или изображение",
            ["Dialog_ImageFilter"] = "Изображения и значки (*.png;*.ico;*.jpg;*.jpeg;*.bmp)|*.png;*.ico;*.jpg;*.jpeg;*.bmp|Все файлы (*.*)|*.*",

            ["Config_NotFound"] = "Предыдущая конфигурация не найдена. Созданы стандартные настройки в AppData.",
            ["Config_ReadError"] = "Файл конфигурации поврежден или не может быть прочитан. Восстановлены значения по умолчанию.",

            ["AutoStart_Prompt"] = "Запускать DockBar автоматически при включении компьютера?",
            ["AutoStart_Title"] = "Автозапуск",

            ["Update_Title"] = "Обновление DockBar",
            ["Update_Subtitle"] = "Доступна новая версия DockBar с улучшениями и исправлениями.",
            ["Update_Checking"] = "Проверка обновлений...",
            ["Update_LatestTitle"] = "DockBar обновлен",
            ["Update_LatestBody"] = "У вас установлена последняя версия ({0}).",
            ["Update_Available"] = "Доступна новая версия ({0}). Скачать и установить сейчас?",
            ["Update_AvailableTitle"] = "Доступна новая версия",
            ["Update_AvailableBody"] = "Текущая версия: {0}\nНовая версия: {1}\n\nОбновить сейчас?",
            ["Update_CheckFailed"] = "Не удалось проверить наличие обновлений.",
            ["Update_UpToDate"] = "DockBar уже обновлен до последней версии ({0}).",
            ["Update_NoInstaller"] = "Не найден установщик для версии {0}.",
            ["Update_CurrentVersion"] = "Текущая версия",
            ["Update_NewVersion"] = "Новая версия",
            ["Update_InstallNow"] = "Обновить сейчас",
            ["Update_Later"] = "Позже",
            ["Update_Changelog"] = "Что нового в этой версии",
            ["Update_NoChangelog"] = "Эта версия содержит оптимизации и общее повышение производительности.",
            ["Update_StatusReady"] = "Готово к загрузке и установке обновления.",
            ["Update_StatusDownloading"] = "Загрузка обновления...",
            ["Update_StatusDownloaded"] = "Загрузка завершена. Запуск установщика...",
            ["Update_Downloading"] = "Загрузка обновления...",
            ["Update_DownloadFailed"] = "Не удалось загрузить обновление.",
            ["Update_ErrorTitle"] = "Ошибка проверки обновлений",
            ["Update_ErrorBody"] = "Произошла ошибка при проверке наличия обновлений.",
            ["Update_PackagedManaged"] = "DockBar установлен как пакет MSIX. Обновления управляются автоматически через Microsoft Store / Windows.",
            ["Update_OpenReleasePage"] = "Посмотреть на GitHub",

            ["About_Title"] = "О программе DockBar",
            ["About_Subtitle"] = "Информация о системе и текущей версии",
            ["About_Version"] = "Версия",
            ["About_UnknownVersion"] = "неизвестно",
            ["About_DeveloperCaption"] = "Разработчик",
            ["About_DeveloperName"] = "Eliather",
            ["About_DescriptionText"] = "Боковая dock-панель быстрого доступа для Windows.",
            ["About_ConfigLabel"] = "Файл конфигурации",
            ["About_DevelopedBy"] = "Разработчик: Eliather",
            ["About_Description"] = "Описание: боковая dock-панель быстрого доступа для Windows.",
            ["About_ConfigPath"] = "Конфигурация: %AppData%\\DockBar\\shortcuts.json"
        },
        ["zh"] = new Dictionary<string, string>
        {
            ["Common_Save"] = "保存",
            ["Common_Apply"] = "应用",
            ["Common_Cancel"] = "取消",
            ["Common_Close"] = "关闭",
            ["Common_Add"] = "添加",
            ["Common_About"] = "关于",
            ["Common_Page"] = "页",

            ["Settings_Title"] = "设置",
            ["Settings_Subtitle"] = "定制专属侧边栏：实时预览并调整尺寸、响应速度和视觉外观。",
            ["Settings_Size"] = "尺寸",
            ["Settings_SizeHint"] = "设置侧边栏宽度以及快捷方式图标大小。",
            ["Settings_DockWidth"] = "侧边栏宽度 (像素)",
            ["Settings_IconSize"] = "图标大小 (像素)",
            ["Settings_AutoHide"] = "自动隐藏与动画",
            ["Settings_BehaviorHint"] = "调整弹出和隐藏速度，让交互更加顺畅自然。",
            ["Settings_HideDelay"] = "隐藏延迟（秒，0 = Win8 风格即时隐藏）",
            ["Settings_AnimDuration"] = "隐藏/弹出动画时长 (毫秒)",
            ["Settings_AutoStart"] = "开机自启动",
            ["Settings_ColorTransparency"] = "颜色与 Glass 效果",
            ["Settings_AppearanceHint"] = "调整基础颜色，并选择使用 Glass 磨砂效果或纯色背景。",
            ["Settings_UseTransparency"] = "启用 Glass 磨砂效果",
            ["Settings_Opacity"] = "不透明度",
            ["Settings_GlassEffect"] = "Glass 效果",
            ["Settings_GlassOn"] = "已开启",
            ["Settings_GlassOff"] = "已关闭",
            ["Settings_ColorPicker"] = "颜色选择器 (HEX 与调色板)",
            ["Settings_ColorPickerBg"] = "背景颜色 (HEX 与调色板)",
            ["Settings_ColorPickerAccent"] = "强调/按钮颜色 (HEX 与调色板)",
            ["Settings_ColorTarget"] = "当前自定义元素：",
            ["Settings_ColorTargetBg"] = "🎨 侧边栏背景",
            ["Settings_ColorTargetAccent"] = "⚡ 强调色 / 按钮",
            ["Settings_ColorHint"] = "使用 HSV 色板选取颜色或手动输入 HEX 十六进制值。",
            ["Settings_Preview"] = "预览",
            ["Settings_PreviewHint"] = "快速参考背景、文字和整体界面的视觉平衡。",
            ["Settings_PreviewSummary"] = "当前配置摘要",
            ["Settings_HexLabel"] = "HEX 颜色",
            ["Settings_HexLabelBg"] = "HEX (背景)",
            ["Settings_HexLabelAccent"] = "HEX (强调色)",
            ["Settings_ColorPalette"] = "推荐配色 (背景)",
            ["Settings_ColorPaletteHint"] = "预设经典配色，省去从零配色的繁琐。",
            ["Settings_AccentPalette"] = "强调配色 (按钮与控件)",
            ["Settings_AccentPaletteHint"] = "用于操作按钮、滑块和交互式控件的对比强调色。",
            ["Settings_TextColor"] = "文字颜色：",
            ["Settings_TextLight"] = "浅色 (白色)",
            ["Settings_TextDark"] = "深色 (黑色)",
            ["Settings_TextShadow"] = "文字阴影：",
            ["Settings_TextShadowOption"] = "文字动态投影",
            ["Settings_DefaultConfig"] = "恢复默认",
            ["Settings_FooterHint"] = "所有更改在保存前都会实时同步反映在预览中。",
            ["Settings_TabBasic"] = "基础设置",
            ["Settings_TabClock"] = "时钟",
            ["Settings_TabMedia"] = "多媒体",
            ["Settings_TabExperimental"] = "实验性功能",
            ["Settings_ExperimentalBanner"] = "实验性功能",
            ["Settings_ExperimentalHint"] = "正在积极开发中以拓展 DockBar 能力的新功能。",
            ["Settings_ExperimentalEmptyTitle"] = "暂无进行中的实验性功能",
            ["Settings_ExperimentalEmptyHint"] = "目前没有激活的实验性功能。后续开发的新特性将在此呈现。",
            ["Settings_ShowResourceMonitor"] = "资源监视器 (CPU、内存与 GPU)",
            ["Settings_ShowResourceMonitorDesc"] = "在侧边栏实时显示处理器、内存及显卡(GPU)占用。点击打开任务管理器。",
            ["Settings_ShowCaffeine"] = "Caffeine 模式 (保持屏幕常亮)",
            ["Settings_ShowCaffeineDesc"] = "在侧边栏添加一个按钮，一键防止屏幕关闭或电脑进入睡眠。",
            ["Dock_CaffeineActiveTooltip"] = "Caffeine：已激活 (屏幕保持常亮)&#x0a;点击停用",
            ["Dock_CaffeineInactiveTooltip"] = "Caffeine：未激活 (普通电源模式)&#x0a;点击保持屏幕常亮",
            ["Dock_ResourceMonitorTooltip"] = "系统监视器&#x0a;点击打开任务管理器",
            ["Settings_WidgetResource"] = "系统资源 (CPU/内存/GPU)",
            ["Settings_DetectedGpus"] = "检测到的 GPU",
            ["Settings_DetectedGpuSingle"] = "检测到的 GPU",
            ["Settings_ShowHardwareModelNames"] = "显示硬件型号名称 (CPU / GPU)",
            ["Settings_ShowHardwareModelNamesDesc"] = "在侧边栏显示处理器和显工具体型号（如 i5 210H、RTX 5050、Ryzen 7）以替代通用标签。",
            ["Settings_WidgetCaffeine"] = "Caffeine",
            ["Settings_ClockSection"] = "实时时钟",
            ["Settings_ClockSectionHint"] = "利用侧边栏闲置空间显示时间和日期，类似 Windows 任务栏时钟。",
            ["Settings_ShowClock"] = "在侧边栏上显示时钟",
            ["Settings_Clock24H"] = "24 小时制（例如 14:30）",
            ["Settings_ClockSeconds"] = "显示实时秒数",
            ["Settings_ClockDate"] = "在时间下方显示日期",
            ["Settings_ClockFontSize"] = "时钟字号 (像素)",
            ["Settings_ClockPreview"] = "DockBar 预览",
            ["Settings_DragReorderTooltip"] = "拖动以调整侧边栏小部件顺序",
            ["Settings_WidgetOrderTitle"] = "侧边栏小部件顺序：",
            ["Settings_WidgetClock"] = "时钟",
            ["Settings_WidgetMedia"] = "媒体 / 歌曲标题",
            ["Settings_WidgetVolume"] = "音量",
            ["Settings_WidgetDisabledTag"] = " (已关闭)",
            ["Settings_MoveUp"] = "上移",
            ["Settings_MoveDown"] = "下移",
            ["Settings_TriggerSection"] = "边缘触发热区 (Hotspot)",
            ["Settings_TriggerSectionHint"] = "设置触发侧边栏弹出的屏幕边缘热区像素厚度。调小数值需更贴近边缘。",
            ["Settings_TriggerThickness"] = "边缘触发厚度 (像素)",
            ["Settings_VolumeSection"] = "音量控制器",
            ["Settings_VolumeSectionHint"] = "直接在侧边栏上调节系统音量并一键切换静音。",
            ["Settings_ShowVolume"] = "在侧边栏上显示音量控制器",
            ["Settings_MediaSection"] = "智能媒体播放器",
            ["Settings_MediaSectionHint"] = "连接 Spotify、浏览器（YouTube）和系统播放器，支持跑马灯滚动歌名和播放控制。",
            ["Settings_ShowMedia"] = "在侧边栏上显示媒体控制器",
            ["Settings_ShowMediaSeekBar"] = "显示播放进度条 / 跳转滑块",
            ["Settings_ShowMediaSeekBarDesc"] = "显示时间线和滑块，允许快进或快退音频与视频。",
            ["Dock_MediaPlayPause"] = "播放 / 暂停",
            ["Dock_MediaNext"] = "下一首",
            ["Dock_MediaPrev"] = "上一首",
            ["Dock_MediaNoTrack"] = "暂无播放媒体",
            ["Dock_VolumeMute"] = "静音",
            ["Dock_VolumeUnmute"] = "取消静音",
            ["Settings_ApplyConfirmTitle"] = "确认配置",
            ["Settings_ApplyConfirmMessage"] = "是否保留并应用所做的更改？",
            ["Settings_ApplyCountdownText"] = "将在 {0} 秒后自动还原...",

            ["AddLink_Title"] = "添加应用或快捷方式",
            ["AddLink_Subtitle"] = "输入路径、可执行文件、文件夹或命令，并设置侧边栏显示名称。",
            ["AddLink_Target"] = "路径、可执行文件或命令",
            ["AddLink_TargetHint"] = "支持 .exe、文件夹、URI 或 Windows 兼容命令。",
            ["AddLink_NameOptional"] = "显示名称（可选）",
            ["AddLink_NameHint"] = "若留空，DockBar 将尝试自动识别名称。",
            ["AddLink_ExamplesTitle"] = "常见示例",
            ["AddLink_ExamplesBody"] = "用于添加外部应用、常用文件夹或命令行快捷指令。",
            ["AddLink_ExamplesFooter"] = "若要添加系统已安装应用，请使用“已安装应用...”选择器。",
            ["AddLink_ValidationEmpty"] = "请在保存前输入有效路径、URI 或命令。",
            ["AddLink_ValidationInvalid"] = "路径或命令无效。请输入有效的文件、文件夹、URI 或系统命令。",

            ["Rename_Title"] = "重命名快捷方式",
            ["Rename_Subtitle"] = "更改快捷方式的显示名称，不会修改其源目标。",
            ["Rename_NewName"] = "新名称",

            ["Store_Title"] = "已安装应用",
            ["Store_Subtitle"] = "浏览 Windows 检测到的应用程序，并使用系统图标添加到侧边栏。",
            ["Store_Search"] = "搜索应用",
            ["Store_SearchHint"] = "可按显示名称、内部标识符或包名搜索。",
            ["Store_Refresh"] = "刷新",
            ["Store_RefreshTooltip"] = "重新扫描已安装的应用",
            ["Store_Loading"] = "正在加载已安装应用...",
            ["Store_Empty"] = "未找到已安装的应用。",
            ["Store_NoApps"] = "未找到已安装的应用。",
            ["Store_PanelTitle"] = "快速选取",
            ["Store_PanelBody"] = "专为轻松添加系统应用而设计，无需手动查找路径。",
            ["Store_PanelTipOneTitle"] = "包含内容",
            ["Store_PanelTipOneBody"] = "UWP 应用、系统快捷方式以及已识别的可执行程序。",
            ["Store_PanelTipTwoTitle"] = "挑选建议",
            ["Store_PanelTipTwoBody"] = "若遇到同名项，可通过查看下方的标识符进行区分。",
            ["Store_PanelFooter"] = "双击也可直接添加所选应用。",
            ["Store_FooterHint"] = "双击也可直接添加所选应用。",

            ["Tray_Open"] = "打开",
            ["Tray_ToggleSide"] = "切换屏幕侧边",
            ["Tray_Settings"] = "设置...",
            ["Tray_ConfigFolder"] = "配置文件目录",
            ["Update_Menu"] = "检查更新...",
            ["Tray_Exit"] = "退出",

            ["AddMenu_File"] = "文件 / 可执行程序...",
            ["AddMenu_Store"] = "已安装应用...",
            ["AddMenu_Uri"] = "命令 / URI 链接...",
            ["Dock_TooltipAdd"] = "添加快捷方式",
            ["Dock_TooltipSettings"] = "打开设置",
            ["Dock_TooltipEditMode"] = "切换编辑模式",
            ["Dock_TooltipClose"] = "关闭 DockBar",
            ["Dock_TooltipRename"] = "重命名",
            ["Dock_TooltipChangeIcon"] = "更改图标",
            ["Dock_TooltipRemove"] = "删除快捷方式",

            ["Dialog_SelectShortcutTitle"] = "选择快捷方式或可执行文件",
            ["Dialog_ExecutableFilter"] = "可执行文件与快捷方式 (*.exe;*.lnk;*.url)|*.exe;*.lnk;*.url|所有文件 (*.*)|*.*",
            ["Dialog_SelectIconTitle"] = "选择图标或图片",
            ["Dialog_ImageFilter"] = "图片与图标 (*.png;*.ico;*.jpg;*.jpeg;*.bmp)|*.png;*.ico;*.jpg;*.jpeg;*.bmp|所有文件 (*.*)|*.*",

            ["Config_NotFound"] = "未找到历史配置文件。已在 AppData 中创建默认配置。",
            ["Config_ReadError"] = "配置文件损坏或无法读取。已恢复默认配置。",

            ["AutoStart_Prompt"] = "是否允许 DockBar 在开机时自动启动？",
            ["AutoStart_Title"] = "开机启动",

            ["Update_Title"] = "DockBar 更新",
            ["Update_Subtitle"] = "检测到 DockBar 新版本，包含多项功能改进与修复。",
            ["Update_Checking"] = "正在检查更新...",
            ["Update_LatestTitle"] = "已是最新版本",
            ["Update_LatestBody"] = "当前使用的已是最新版本 ({0})。",
            ["Update_Available"] = "发现新版本 ({0})。是否立即下载并安装？",
            ["Update_AvailableTitle"] = "发现新版本",
            ["Update_AvailableBody"] = "当前版本: {0}\n最新版本: {1}\n\n是否立即更新？",
            ["Update_CheckFailed"] = "暂时无法检查更新。",
            ["Update_UpToDate"] = "DockBar 已是最新版本 ({0})。",
            ["Update_NoInstaller"] = "未找到版本 {0} 的安装程序。",
            ["Update_CurrentVersion"] = "当前版本",
            ["Update_NewVersion"] = "新版本",
            ["Update_InstallNow"] = "立即更新",
            ["Update_Later"] = "稍后提醒",
            ["Update_Changelog"] = "更新日志",
            ["Update_NoChangelog"] = "本次更新包含多项性能优化与通用改进。",
            ["Update_StatusReady"] = "已就绪，可开始下载并安装更新。",
            ["Update_StatusDownloading"] = "正在下载更新...",
            ["Update_StatusDownloaded"] = "下载完成。正在启动安装程序...",
            ["Update_Downloading"] = "正在下载更新...",
            ["Update_DownloadFailed"] = "下载更新失败。",
            ["Update_ErrorTitle"] = "检查更新出错",
            ["Update_ErrorBody"] = "检查更新时发生异常。",
            ["Update_PackagedManaged"] = "DockBar 作为 MSIX 包运行。更新将由 Microsoft Store / Windows 自动管理。",
            ["Update_OpenReleasePage"] = "在 GitHub 上查看",

            ["About_Title"] = "关于 DockBar",
            ["About_Subtitle"] = "系统信息与当前版本",
            ["About_Version"] = "版本",
            ["About_UnknownVersion"] = "未知",
            ["About_DeveloperCaption"] = "开发者",
            ["About_DeveloperName"] = "Eliather",
            ["About_DescriptionText"] = "专为 Windows 打造的轻量级侧边快捷栏。",
            ["About_ConfigLabel"] = "配置文件路径",
            ["About_DevelopedBy"] = "由 Eliather 开发",
            ["About_Description"] = "描述：专为 Windows 打造的侧边快捷栏。",
            ["About_ConfigPath"] = "配置路径: %AppData%\\DockBar\\shortcuts.json"
        }
    };

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Strings = BuildReadOnlyStrings();

    private static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> BuildReadOnlyStrings()
    {
        var dict = new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase);
        foreach (var langKvp in RawStrings)
        {
            dict[langKvp.Key] = new ReadOnlyDictionary<string, string>(
                new Dictionary<string, string>(langKvp.Value, StringComparer.OrdinalIgnoreCase));
        }

        return new ReadOnlyDictionary<string, IReadOnlyDictionary<string, string>>(dict);
    }

    private static string _language = GetDefaultLanguage();

    public static void SetLanguage(string? language)
    {
        var normalized = NormalizeLanguage(language);
        _language = normalized;
    }

    public static string Get(string key)
    {
        if (string.IsNullOrWhiteSpace(key))
        {
            return string.Empty;
        }

        var lang = _language;
        if (Strings.TryGetValue(lang, out var dict) && dict.TryGetValue(key, out var value))
        {
            return value;
        }

        // Fallback chain: English -> Spanish -> Raw Key
        if (Strings.TryGetValue("en", out var enDict) && enDict.TryGetValue(key, out var enValue))
        {
            return enValue;
        }

        if (Strings.TryGetValue("es", out var fallback) && fallback.TryGetValue(key, out var esValue))
        {
            return esValue;
        }

        return key;
    }

    private static string GetDefaultLanguage()
    {
        var lang = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        return NormalizeLanguage(lang);
    }

    private static string NormalizeLanguage(string? language)
    {
        if (string.Equals(language, "es", StringComparison.OrdinalIgnoreCase))
        {
            return "es";
        }

        if (string.Equals(language, "ru", StringComparison.OrdinalIgnoreCase))
        {
            return "ru";
        }

        if (string.Equals(language, "zh", StringComparison.OrdinalIgnoreCase))
        {
            return "zh";
        }

        return "en";
    }
}
